index.js
Fixed #3.
Proof: ![grafik](https://user-images.githubusercontent.com/30803034/127041250-a3c7913e-65b2-4804-9033-f55f977fbbe2.png)
I'm gonna send it to Discord as well.
=> Made $catch Case Insensitive

index.js, pokemon.js
Fixes Issue #5.
Proof:
Below another case insensitivity test and the design of the the message if the pokemon got caught in english
=> Added multilanguage support

index.js, leaderboard.js
Fixes #9. Needs to be updated when the bot is switched over to ids.
=> Added ability for getting position by mentioning

util.js
I updated the credits because you said you would credit anyone who helps. You don't need to merge if you don't want to
=> Updated Credits in embedReply

leaderboard.js
Null-Check for !position and $leaderboard
Udpated $position for myself when not on leaderboard
Prevented crash on !new championship when no one is in the leaderboard
Working position for myself when i have something caught
Working position for someone else
I hope i haven't forgotten some proofs or tests
=> Added some null-checks and updated $position for ids

index.js, leaderboard.js
These commands can manipulate the score and remove/add users from/to the leaderboard. I screenshoted 4 images as proof:
This fixes #17
=> Added !addscore and !removescore

util.js
Proof (I hope i didn't make some grammatical mistakes):
=> Updated adminHelp for !addscore and !removescore

index.js
Saved the Names from the fetchNames function on !explore
Proof:
=> Fixed #11 by saving the names to db

README.md
Changed `addscore <@user> <score>` to `!addscore <@user> <score>`
=> Added missing exclamation mark

index.js, pokemon.js
=> Merge changes from develop into master

index.js, pokemon.js
=> Hopefully fixed the problem with the weird names by using a id

disadvantages.js, index.js
Fixes #38 
I think it doesn't have to be too complex so i just made the command in the following format:
`year/month/day[/hour/minute/second/millisecond]`
The Commit message said something like event not found so i did \ in front which worked.
I just adding !showtimeout because i forgot to implement this in the last commit so there'll be 2 commits
proof:
=> Added !timeout, !untimeout, !showtimeout

leaderboard.js
I have tested it with !leaderboard and $position. In those cases it worked for the server I'm alone in
=> Made leaderboard.js able to get the usernames of uncached users

settings.js
I apparently forgot to remove a function. I created that file through copying help.js and then modifying it and that's how this occured. My Test probably was successful because the function maybe got overwritten by the second one.
=> Removed duplicate function

data/db.js
=> Removed redundant lines

data/postgres.js, leaderboard.js, score.js, settings.js
Haven't tried it with users in the database but apart from that all tests worked.
I'll check if it works with stored scores when I have those score manipulation functions in mod.js implemented.
Also I cleaned up leaderboard.js and added an semicolon in settings.js
=> Made /score show work

catch.js, explore.js, util.js
replaced <guesser> with the guessers mention
fixed images not shown (discord.js made a breaking change to how to attach files to messages)
=> Fixed two things:

README.md
A few adjustments.
For the part of registering the slash commands: you don't register them with a discord server to be exact because the bot uses so called global commands meaning those work on all servers without having to create them for every server individually.
=> Minor adjustments to README.md

Dockerfile, data/postgres.js
The Bot still works through Docker
=> Let Snyk run to check for vulerabilities

Dockerfile, catch.js, championship.js, commands.js, delay.js, explore.js, help.js, index.js, leaderboard.js, mod.js, package.json, pokemon.js, reveal.js, score.js, settings.js, setupCommands.js, timeout.js, util.js
I  have changed the discord.js dependency from v13 to v14 and fixed breaking changes with the help of [this website](https://discordjs.guide/additional-info/changes-in-v14.html)
And because I didn't pull beforehand  because `git status` said there is nothing new I had to merge my local repo with the remote one (with the help of my brother)
I hope I tested everything important. I tested `/settings`, `/score show`, `/explore`, `/catch` and `/reveal`
=> Bumped discord.js v13 to discord.js v14

util.js
Pokketmuse's new name is Valley Orion
Draft as I have not tested the change yet
=> Changed Footer Name

.github/workflows/docker-image.yml, docker-compose-gh-action.yml
I made a `docker-image.yml` file for the action itself and a `docker-compose-gh-action.yml` for that the action is not trying to load docker.env which is listed in both the `docker-compose.yml` and `.gitignore`.
It worked in my repository.
=> Added GitHub Action Workflow to check docker-compose build

catch.js, commands.js, docker-compose.yml, index.js, languages/de_DE.json, languages/en_US.json, setupCommands.js
* Removed registering of /catch with discord
* Removed the catch function exports
* Removed the catch function
* Removed calling of the catch function
* Upgraded postgres in docker-compose.yml to version 15
This PR is a draft because I haven't tested any of my changes yet apart from the GitHub Actions Test
=> Removed /catch

index.js
I just removed the feature of creating a new disabled button to attach to the explore message and simply removed the button if the guess is correct
Proof:
=> Removed button on correct guess

util.js
Use color from parameter instead of hardcoding it and not using the given optional parameter
=> fix: Use Color from Parameter in returnEmbed

.ci/docker-compose.yml, .github/workflows/docker-image.yml, Dockerfile, docker-compose.yml
=> Fix Docker Compose CI

catch.ts, championship.ts, delay.ts, explore.ts, help.ts, index.ts, languages/en_US.json, leaderboard.ts, mod.ts, score.ts, settings.ts, timeout.ts, util.ts
This PR just added a few missing parts where the language gets loaded and has a few fixed I found while doing it.
=> Make sure every string that gets output to the user to come from the language json files

mod.ts, settings.ts
Score add without number doesnt set
Score set 0 didn't work (probably nullable check)
=> Fix what I noted about the score commands not working

.github/workflows/jest.yml, index.ts, package.json, test/index.test.ts
* Removed unnecessary line in `index.ts`
* Add Jest config to `package.json`
* Created GitHub Actions CI/CD Pipeline for testing with jest
* Added demo test to test file because jest wants to have at least 1 test suite
Fixes #98 
Closes #99
=> Fix jest and add jest CI

.vscode/settings.json, README.md, data/postgres.ts, explore.ts, help.ts, index.ts, leaderboard.ts, mod.ts, reveal.ts, score.ts, settings.ts
I removed checks for guild and guildId which was already being checked in `index.ts`. I also modified `postgres.ts` to stop outputting endless logs, but this can be disabled if needed.
=> Remove redundant checks in command modules

.github/workflows/prettier.yml, src/commands.ts, src/setupCommands.ts
=> Simplify setupCommands.ts and prettier workflow

src/index.ts
See https://github.com/motdotla/dotenv?tab=readme-ov-file#how-do-i-use-dotenv-with-import
=> Update dotenv import to recommended method

.github/workflows/docker-image.yml, Dockerfile
See https://docs.docker.com/compose/migrate/, https://github.com/actions/runner-images/issues/9557, https://github.com/actions/runner-images/pull/9559 and https://github.com/actions/runner-images/pull/9617
=> Migrate to Docker Compose V2
